language: ruby
rvm:
# TODO: reenable once tests pass with 4.0
  - 2.0.0
  - 1.9.3
#  - 1.8.7 # < predictably wedges travis builds
  # - jruby-19mode
  # - rbx-19mode

gemfile:
# TODO: reenable once tests pass with 4.0
  - ci/Gemfile.rails-4.0.x
  - ci/Gemfile.rails-3.2.x
  - ci/Gemfile.rails-3.1.x
  - ci/Gemfile.rails-3.0.x

env:
# TODO: reenable once tests pass with 4.0
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace all_spec_flavors

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: ci/Gemfile.rails-4.0.x
      env: DB=sqlite
    - rvm: 1.8.7
      gemfile: ci/Gemfile.rails-4.0.x
      env: DB=mysql
    - rvm: 1.8.7
      gemfile: ci/Gemfile.rails-4.0.x
      env: DB=postgresql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.0.x
      env: DB=sqlite
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.0.x
      env: DB=mysql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.0.x
      env: DB=postgresql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.1.x
      env: DB=sqlite
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.1.x
      env: DB=mysql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.1.x
      env: DB=postgresql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.2.x
      env: DB=sqlite
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.2.x
      env: DB=mysql
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails-3.2.x
      env: DB=postgresql
