language: ruby
rvm:
  - 2.1.2
  - 1.9.3

gemfile:
  - ci/Gemfile.rails-4.1.x
  - ci/Gemfile.rails-4.0.x
  - ci/Gemfile.rails-3.2.x

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace all_spec_flavors
