cache: bundler
sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.0
  - jruby-head
  - rbx

gemfile:
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace spec:all

matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: jruby-head
    - rvm: rbx

  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_4.1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5.0.gemfile
