common: &common
  database: closure_tree_test
  host: localhost
  pool: 50
  timeout: 5000
  reaping_frequency: 1000
  min_messages: ERROR

sqlite:
  adapter: sqlite3
  database: ':memory:'

postgresql:
  <<: *common
  adapter: postgresql
  username: postgres

mysql:
  <<: *common
  adapter: mysql2
  username: root
