common: &common
  database: closure_tree_test
  host: localhost
  pool: 50
  timeout: 5000
  reaping_frequency: 1000
  min_messages: ERROR

sqlite:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: spec/sqlite3.db

postgresql:
  <<: *common
  adapter: postgresql
  username: postgres

mysql:
  <<: *common
  adapter: mysql2
  username: root
